version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: |
      /bin/bash -c 'echo "Hello World" | kafka-console-producer --bootstrap-server kafka:9092 --topic test-topic'

  consumer:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: "/bin/bash -c 'kafka-console-consumer --bootstrap-server kafka:9092 --topic test-topic --from-beginning'"
